# Generated by Django 3.1.5 on 2024-09-02 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrefamilia', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'FamiliaMenu',
                'verbose_name_plural': 'FamiliaMenus',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FormadePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopago', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FormadePago',
                'verbose_name_plural': 'FormadePagos',
                'ordering': ['tipopago'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidaddemenu', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ModalidadMenu',
                'verbose_name_plural': 'ModalidadMenus',
                'ordering': ['modalidaddemenu'],
            },
        ),
        migrations.CreateModel(
            name='Tablas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('linkpagina', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'tabla',
                'verbose_name_plural': 'tablas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Temp_FamiliaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia', models.IntegerField()),
                ('nombrefamilia', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Temp_FamiliaMenu',
                'verbose_name_plural': 'Temp_FamiliaMenus',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodemenu', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TipoMenu',
                'verbose_name_plural': 'TipoMenus',
                'ordering': ['tipodemenu'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreformulario', models.CharField(max_length=50)),
                ('nombrevista', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tablas')),
            ],
            options={
                'verbose_name': 'pagina',
                'verbose_name_plural': 'paginas',
            },
        ),
        migrations.CreateModel(
            name='CartaMenu_enFila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremenu', models.CharField(max_length=50)),
                ('costomenu', models.FloatField()),
                ('id_plato', models.IntegerField()),
                ('fotomenu', models.ImageField(blank=True, null=True, upload_to='administracion')),
                ('detallemenu', models.TextField(null=True)),
                ('juvenil', models.BooleanField(null=True)),
                ('mayor', models.BooleanField(null=True)),
                ('normal', models.BooleanField(null=True)),
                ('celiaco', models.BooleanField(null=True)),
                ('vegano', models.BooleanField(null=True)),
                ('vegetariano', models.BooleanField(null=True)),
                ('tipofamilia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.familiamenu')),
            ],
            options={
                'verbose_name': 'cartamenu_enfila',
                'verbose_name_plural': 'cartamenus_enfila',
                'ordering': ['id_plato'],
            },
        ),
        migrations.CreateModel(
            name='CartaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremenu', models.CharField(max_length=50)),
                ('fotomenu', models.ImageField(blank=True, null=True, upload_to='administracion')),
                ('detallemenu', models.TextField(null=True)),
                ('costomenu', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('id_plato', models.IntegerField()),
                ('tipofamilia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.familiamenu')),
                ('tipomenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.tipomenu')),
                ('tipomodalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.modalidadmenu')),
            ],
            options={
                'verbose_name': 'cartamenu',
                'verbose_name_plural': 'cartamenus',
                'ordering': ['id_plato'],
            },
        ),
        migrations.CreateModel(
            name='Usuarioregistrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=50)),
                ('mailusuario', models.CharField(max_length=50)),
                ('passwordusuario', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuarioregistrado',
                'verbose_name_plural': 'usuarioregistrados',
                'ordering': ['nombreusuario'],
                'unique_together': {('usuario',)},
            },
        ),
    ]
