# Generated by Django 2.1.15 on 2024-09-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartamenu',
            name='id_plato',
            field=models.IntegerField(auto_created=True),
        ),
    ]
