# Generated by Django 3.1.5 on 2024-09-02 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecliente', models.CharField(max_length=50, null=True)),
                ('numcliente', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('sexo', models.CharField(max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('tipodocunento', models.CharField(max_length=5)),
                ('numdocumento', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombrecliente'],
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='Contrato2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_comtrato', models.CharField(max_length=50)),
                ('fechaevento', models.DateTimeField(null=True)),
                ('estadoevento', models.CharField(default='pendiente', max_length=15)),
                ('estadopago', models.CharField(default='pendiente', max_length=15)),
                ('fotocontrato', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('montooriginal', models.FloatField(null=True)),
                ('montoactualizado', models.FloatField(null=True)),
                ('saldopendiente', models.FloatField(null=True)),
                ('TarjetasPendientes', models.FloatField(null=True)),
                ('Valortarj_actualizado', models.FloatField(null=True)),
                ('cant_tarj_contratadas', models.IntegerField(null=True)),
                ('TarjetasPagadas', models.FloatField(null=True)),
                ('TotalGastos', models.FloatField(null=True)),
                ('Diferencia', models.FloatField(null=True)),
                ('porcentaje', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('tipoevento', models.ManyToManyField(to='servicios.Servicio')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['cliente_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.TextField()),
                ('direccion', models.TextField(null=True)),
                ('CUIT', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razonsocial'],
            },
        ),
        migrations.CreateModel(
            name='TotalGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montogasto', models.FloatField(null=True)),
                ('montoingreso', models.FloatField(null=True)),
                ('diferencia', models.FloatField(null=True)),
                ('porcentaje', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('familiamenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.familiamenu')),
            ],
            options={
                'verbose_name': 'TotalGasto',
                'verbose_name_plural': 'TotalGastos',
                'ordering': ['cliente_id', 'contrato_id', 'familiamenu_id'],
            },
        ),
        migrations.CreateModel(
            name='TotalContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_tarjetas', models.IntegerField()),
                ('costo_tarjeta', models.FloatField()),
                ('tot_tarjetas', models.FloatField()),
                ('tot_comunes', models.FloatField()),
                ('tot_adicionales', models.FloatField()),
                ('tot_logistica', models.FloatField()),
                ('tot_contrato', models.FloatField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
            ],
            options={
                'verbose_name': 'TotalContrato',
                'verbose_name_plural': 'TotalContratos',
                'ordering': ['id_contrato_id'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_tarjetas', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('costo_tarjeta', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('modalidaddelmenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.modalidadmenu')),
                ('tipodemenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.tipomenu')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['contrato_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SumaGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalgastos', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
            ],
            options={
                'verbose_name': 'SumaGasto',
                'verbose_name_plural': 'SumaGastos',
                'ordering': ['cliente_id', 'contrato_id'],
            },
        ),
        migrations.CreateModel(
            name='SumaContrato2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
            ],
            options={
                'verbose_name': 'SumaContrato',
                'verbose_name_plural': 'SumaContratos',
            },
        ),
        migrations.CreateModel(
            name='SumaActualizacion2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
            ],
            options={
                'verbose_name': 'SumaActualizacion',
                'verbose_name_plural': 'SumaActualizacions',
            },
        ),
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_item', models.FloatField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('id_familiamenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.familiamenu')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cartamenu')),
            ],
            options={
                'verbose_name': 'ServicioContratado',
                'verbose_name_plural': 'ServicioContratados',
                'ordering': ['id_contrato_id'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_item', models.FloatField()),
                ('detalleservicio', models.TextField(null=True)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('id_familiamenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.familiamenu')),
            ],
            options={
                'verbose_name': 'ServicioAdicional',
                'verbose_name_plural': 'ServiciosAdicionales',
                'ordering': ['id_contrato_id'],
            },
        ),
        migrations.CreateModel(
            name='Pagos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_pago', models.CharField(max_length=50)),
                ('fechapago', models.DateTimeField()),
                ('monto', models.FloatField()),
                ('numcomprobante', models.IntegerField(null=True)),
                ('imagencomprobante', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('costo_tarjeta', models.FloatField(null=True)),
                ('tarjetas_pend', models.FloatField(null=True)),
                ('deuda_a_la_fecha', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('formadepago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.formadepago')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pagos',
                'ordering': ['cliente_id', 'contrato_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_item', models.FloatField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('id_familiamenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.familiamenu')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cartamenu')),
                ('id_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tarjeta')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['id_contrato_id', 'id_tarjeta_id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numfactura', models.IntegerField(null=True)),
                ('fechagasto', models.DateTimeField()),
                ('montogasto', models.FloatField()),
                ('fechapago', models.DateTimeField()),
                ('detallecompra', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('familiamenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.familiamenu')),
                ('formadepago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.formadepago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.proveedor')),
            ],
            options={
                'verbose_name': 'DetalleGasto',
                'verbose_name_plural': 'DetalleGastos',
                'ordering': ['cliente_id', 'contrato_id', 'familiamenu_id'],
            },
        ),
        migrations.CreateModel(
            name='ControlTarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_tarjetas_pagas', models.FloatField()),
                ('cant_tarjetas_pendientes', models.FloatField()),
                ('costo_tarjeta_actualizado', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pagos2')),
            ],
            options={
                'verbose_name': 'ControlTarjeta',
                'verbose_name_plural': 'ControlTarjetas',
                'ordering': ['cliente_id', 'contrato_id', 'pago_id'],
            },
        ),
        migrations.CreateModel(
            name='ActualizacionContrato2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldopendiente', models.FloatField()),
                ('fechaactualizacion', models.DateTimeField(null=True)),
                ('porcentaje', models.FloatField()),
                ('incremento', models.FloatField()),
                ('aplicado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente2')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato2')),
            ],
            options={
                'verbose_name': 'ActualizacionContrato',
                'verbose_name_plural': 'ActualizacionContratos',
                'ordering': ['cliente_id', 'contrato_id', 'id'],
            },
        ),
    ]
